import type { CSSProperties } from "react";
import { baseFont } from "../editorStyles";

export const inlineStyles = {
  toolbar: {
    position: "absolute",
    zIndex: 8,
    display: "inline-flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    minHeight: 36,
    maxWidth: "calc(100% - 16px)",
    padding: "4px 6px",
    borderRadius: 7,
    border: "1px solid rgba(255,255,255,0.18)",
    background: "rgba(16,20,30,0.94)",
    boxShadow: "0 12px 34px rgba(0,0,0,0.28)",
  },
  iconButton: {
    width: 28,
    height: 28,
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#151a25",
    color: "#f4f6fa",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
  },
  iconButtonActive: {
    borderColor: "#d4a24c",
    background: "#2c2418",
    color: "#ffd991",
  },
  dangerButton: {
    borderColor: "#ff8a8f",
    background: "#b4232a",
    color: "#fff",
  },
  numberInput: {
    width: 54,
    height: 28,
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    color: "#f4f6fa",
    padding: "0 6px",
    font: `12px ${baseFont}`,
    outline: "none",
  },
  colorInput: {
    width: 30,
    height: 28,
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    padding: 3,
    cursor: "pointer",
  },
  select: {
    height: 28,
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    color: "#f4f6fa",
    padding: "0 7px",
    font: `12px ${baseFont}`,
    outline: "none",
    cursor: "pointer",
  },
  fileButton: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#151a25",
    color: "#f4f6fa",
    padding: "0 9px",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  actionButton: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #d4a24c",
    background: "#2c2418",
    color: "#ffd991",
    padding: "0 9px",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  opacityInput: {
    width: 74,
    accentColor: "#d4a24c",
    cursor: "pointer",
  },
  textEditor: {
    position: "absolute",
    zIndex: 7,
    boxSizing: "border-box",
    border: "1px solid #6f93ff",
    outline: "none",
    resize: "none",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    background: "rgba(255,255,255,0.02)",
  },
} satisfies Record<string, CSSProperties>;
