import type { CSSProperties } from "react";
import { baseFont } from "../editorStyles";

export const layoutStyles = {
  shell: {
    display: "flex",
    width: "100%",
    height: "100dvh",
    overflow: "hidden",
    background: "#0a0d14",
    color: "#e6ebf5",
    fontFamily: baseFont,
  },
  sidebar: {
    width: 230,
    flexShrink: 0,
    borderRight: "1px solid #20283a",
    background: "#10141e",
    display: "flex",
    flexDirection: "column",
  },
  header: { padding: 18, borderBottom: "1px solid #20283a" },
  titleInput: {
    marginTop: 8,
    width: "100%",
    border: "none",
    background: "transparent",
    color: "#f4f6fa",
    fontSize: 18,
    fontWeight: 700,
    outline: "none",
    padding: 0,
  },
  meta: { marginTop: 4, fontSize: 12, color: "#7d89a3" },
  thumbs: { flex: 1, overflowY: "auto", padding: 14, display: "grid", gap: 12 },
  thumbRow: {
    display: "grid",
    gridTemplateColumns: "22px 1fr",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: 6,
    border: "1px solid #242c3e",
    borderRadius: 7,
    background: "#0c1019",
    color: "#e6ebf5",
    cursor: "pointer",
  },
  thumbNumber: {
    color: "#7d89a3",
    fontSize: 11,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
  },
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  topbar: {
    height: 62,
    flexShrink: 0,
    padding: "0 22px",
    borderBottom: "1px solid #20283a",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
  },
  currentTitle: { fontSize: 15, fontWeight: 700, color: "#f4f6fa" },
  toolbar: { display: "inline-flex", alignItems: "center", gap: 10 },
} satisfies Record<string, CSSProperties>;
