import type { CSSProperties } from "react";
import { EXPORT_H, EXPORT_W } from "./editorUtils";

const baseFont =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif";

export const styles = {
  shell: {
    display: "flex",
    width: "100vw",
    height: "100vh",
    overflow: "hidden",
    background: "#0a0d14",
    color: "#e6ebf5",
    fontFamily: baseFont,
  },
  sidebar: {
    width: 230,
    flexShrink: 0,
    borderRight: "1px solid #20283a",
    background: "#10141e",
    display: "flex",
    flexDirection: "column",
  },
  header: { padding: 18, borderBottom: "1px solid #20283a" },
  eyebrow: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: 1.8,
    color: "#6a7894",
  },
  titleInput: {
    marginTop: 8,
    width: "100%",
    border: "none",
    background: "transparent",
    color: "#f4f6fa",
    fontSize: 18,
    fontWeight: 700,
    outline: "none",
    padding: 0,
  },
  meta: { marginTop: 4, fontSize: 12, color: "#7d89a3" },
  thumbs: { flex: 1, overflowY: "auto", padding: 14, display: "grid", gap: 12 },
  thumbRow: {
    display: "grid",
    gridTemplateColumns: "22px 1fr",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: 6,
    border: "1px solid #242c3e",
    borderRadius: 7,
    background: "#0c1019",
    color: "#e6ebf5",
    cursor: "pointer",
  },
  thumbNumber: {
    color: "#7d89a3",
    fontSize: 11,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
  },
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  topbar: {
    height: 62,
    flexShrink: 0,
    padding: "0 22px",
    borderBottom: "1px solid #20283a",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
  },
  currentTitle: { fontSize: 15, fontWeight: 700, color: "#f4f6fa" },
  toolbar: { display: "inline-flex", alignItems: "center", gap: 10 },
  primaryButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 7,
    border: "none",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
  },
  workArea: {
    flex: 1,
    minHeight: 0,
    display: "flex",
  },
  stagePanel: {
    minWidth: 0,
    minHeight: 0,
    padding: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  slideFrame: {
    position: "relative",
    flexShrink: 0,
  },
  slideEditButton: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 5,
    height: 34,
    padding: "0 14px",
    borderRadius: 7,
    border: "1px solid rgba(255,255,255,0.22)",
    background: "rgba(16,20,30,0.88)",
    color: "#f4f6fa",
    boxShadow: "0 10px 28px rgba(0,0,0,0.28)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  inspector: {
    borderLeft: "1px solid #20283a",
    background: "#10141e",
    padding: 18,
    overflowY: "auto",
  },
  drawerBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    display: "flex",
    justifyContent: "flex-end",
    background: "rgba(3, 7, 18, 0.5)",
  },
  drawer: {
    width: 360,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    background: "#10141e",
    boxShadow: "-24px 0 70px rgba(0,0,0,0.44)",
    padding: 18,
    overflowY: "auto",
  },
  drawerHint: {
    margin: "-6px 0 16px",
    color: "#7d89a3",
    fontSize: 12,
    lineHeight: 1.45,
  },
  inspectorHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 18,
  },
  inspectorTitle: {
    margin: "6px 0 0",
    fontSize: 18,
    lineHeight: 1.2,
    color: "#f4f6fa",
  },
  iconRow: { display: "inline-flex", gap: 8 },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    cursor: "pointer",
    fontSize: 16,
  },
  form: { display: "grid", gap: 14 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  field: {
    display: "grid",
    gap: 7,
    fontSize: 12,
    fontWeight: 700,
    color: "#9aa7bd",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px ${baseFont}`,
    outline: "none",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px/1.4 ${baseFont}`,
    resize: "vertical",
    outline: "none",
  },
  colorInput: {
    width: "100%",
    height: 38,
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    padding: 4,
  },
  toggleRow: { display: "flex", gap: 14 },
  itemList: {
    display: "grid",
    gap: 8,
  },
  itemRow: {
    display: "grid",
    gridTemplateColumns: "1fr 34px",
    gap: 8,
    alignItems: "center",
  },
  gridItemEditor: {
    display: "grid",
    gap: 8,
    padding: 8,
    borderRadius: 7,
    border: "1px solid #20283a",
    background: "#0c1019",
  },
  checkLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: "#d8dfed",
    fontSize: 13,
    fontWeight: 700,
  },
  addGrid: {
    marginTop: 20,
    paddingTop: 18,
    borderTop: "1px solid #20283a",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  secondaryButton: {
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 700,
    cursor: "pointer",
  },
  smallButton: {
    width: 34,
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 800,
    cursor: "pointer",
  },
  segmented: {
    display: "inline-flex",
    padding: 3,
    borderRadius: 8,
    border: "1px solid #2b3448",
    background: "#10141e",
  },
  segment: {
    height: 28,
    padding: "0 10px",
    borderRadius: 6,
    border: "none",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  hiddenStages: {
    position: "fixed",
    left: -10000,
    top: 0,
    width: EXPORT_W,
    height: EXPORT_H,
    overflow: "hidden",
    pointerEvents: "none",
  },
} satisfies Record<string, CSSProperties>;
