import type { CSSProperties } from "react";

export const drawerStyles = {
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    display: "flex",
    justifyContent: "flex-end",
    background: "rgba(3, 7, 18, 0.5)",
  },
  drawer: {
    width: 360,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    background: "#10141e",
    boxShadow: "-24px 0 70px rgba(0,0,0,0.44)",
    padding: 18,
    overflowY: "auto",
  },
  themeDrawer: {
    width: 380,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    background: "#10141e",
    boxShadow: "-24px 0 70px rgba(0,0,0,0.44)",
    padding: 18,
    overflowY: "auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 18,
  },
  title: {
    margin: "6px 0 0",
    fontSize: 18,
    lineHeight: 1.2,
    color: "#f4f6fa",
  },
  iconRow: { display: "inline-flex", gap: 8 },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    cursor: "pointer",
    fontSize: 16,
  },
  hint: {
    margin: "-6px 0 16px",
    color: "#7d89a3",
    fontSize: 12,
    lineHeight: 1.45,
  },
  themePanel: {
    display: "grid",
    gap: 12,
    marginBottom: 16,
    padding: 12,
    borderRadius: 8,
    border: "1px solid #20283a",
    background: "#0c1019",
  },
  themeGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  addGrid: {
    marginTop: 20,
    paddingTop: 18,
    borderTop: "1px solid #20283a",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  generatorPanel: {
    marginTop: 14,
    padding: 12,
    borderRadius: 8,
    border: "1px solid #20283a",
    background: "#0c1019",
    display: "grid",
    gap: 10,
  },
} satisfies Record<string, CSSProperties>;
