import type { CSSProperties } from "react";

export const drawerStyles = {
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    display: "flex",
    justifyContent: "flex-end",
    background: "rgba(3, 7, 18, 0.5)",
  },
  sidecarBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 32,
    background: "rgba(3, 7, 18, 0.18)",
  },
  drawer: {
    width: 360,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    background: "#10141e",
    boxShadow: "-24px 0 70px rgba(0,0,0,0.44)",
    padding: 18,
    overflowY: "auto",
  },
  themeDrawer: {
    width: 380,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    background: "#10141e",
    boxShadow: "-24px 0 70px rgba(0,0,0,0.44)",
    padding: 18,
    overflowY: "auto",
  },
  componentDrawer: {
    width: 340,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    background: "#0b1018",
    boxShadow: "-16px 0 48px rgba(0,0,0,0.32)",
    padding: 18,
    overflowY: "auto",
  },
  slideLayoutDrawer: {
    position: "absolute",
    top: 0,
    width: 330,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    borderRight: "1px solid #20283a",
    background: "#0b1018",
    boxShadow: "-16px 0 48px rgba(0,0,0,0.32)",
    padding: 18,
    overflowY: "auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 18,
  },
  title: {
    margin: "6px 0 0",
    fontSize: 18,
    lineHeight: 1.2,
    color: "#f4f6fa",
  },
  iconRow: { display: "inline-flex", gap: 8 },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    cursor: "pointer",
    fontSize: 16,
  },
  hint: {
    margin: "-6px 0 16px",
    color: "#7d89a3",
    fontSize: 12,
    lineHeight: 1.45,
  },
  themePanel: {
    display: "grid",
    gap: 12,
    marginBottom: 16,
    padding: 12,
    borderRadius: 8,
    border: "1px solid #20283a",
    background: "#0c1019",
  },
  themeGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  addGrid: {
    marginTop: 20,
    paddingTop: 18,
    borderTop: "1px solid #20283a",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  componentPanel: {
    marginTop: 14,
    padding: 12,
    borderRadius: 8,
    border: "1px solid #20283a",
    background: "#0c1019",
    display: "grid",
    gap: 10,
  },
  sectionTitle: {
    color: "#f4f6fa",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 0.4,
  },
  componentGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 8,
  },
  componentButton: {
    minHeight: 44,
    border: "1px solid #2b3448",
    borderRadius: 7,
    background: "#161b27",
    color: "#d8dfed",
    cursor: "pointer",
    display: "grid",
    gap: 3,
    justifyItems: "start",
    padding: "8px 10px",
    textAlign: "left",
  },
  componentName: {
    color: "#f4f6fa",
    fontSize: 12,
    fontWeight: 800,
  },
  componentMeta: {
    color: "#7d89a3",
    fontSize: 11,
  },
  componentSlotGrid: {
    display: "grid",
    gap: 8,
  },
  componentSlotSummary: {
    border: "1px solid #20283a",
    borderRadius: 7,
    background: "#111722",
    color: "#d8dfed",
    fontSize: 12,
    lineHeight: 1.35,
    padding: "9px 10px",
  },
  componentImageSlotRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: 8,
    alignItems: "center",
  },
  componentHint: {
    marginTop: 10,
    color: "#7d89a3",
    fontSize: 11,
    lineHeight: 1.4,
  },
  componentPreviewGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 10,
  },
  componentPreviewCard: {
    border: "1px solid #20283a",
    borderRadius: 8,
    background: "#111722",
    color: "#d8dfed",
    cursor: "pointer",
    display: "grid",
    gap: 7,
    padding: 10,
    textAlign: "left",
  },
  componentPreviewFrame: {
    width: "100%",
    aspectRatio: "16 / 9",
    borderRadius: 6,
    border: "1px solid #273044",
    background: "#0a0d14",
    display: "block",
    overflow: "hidden",
    padding: 8,
    boxSizing: "border-box",
  },
  componentPreviewStage: {
    position: "relative",
    width: "100%",
    height: "100%",
    display: "block",
  },
  componentPreviewName: {
    color: "#f4f6fa",
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1.25,
  },
  componentPreviewMeta: {
    color: "#7d89a3",
    fontSize: 11,
  },
  slideLayoutGrid: {
    display: "grid",
    gap: 12,
  },
  slideLayoutCard: {
    border: "1px solid #20283a",
    borderRadius: 8,
    background: "#111722",
    color: "#d8dfed",
    cursor: "pointer",
    display: "grid",
    gap: 8,
    padding: 10,
    textAlign: "left",
  },
  slideLayoutPreview: {
    display: "block",
    width: "100%",
    aspectRatio: "16 / 9",
    borderRadius: 6,
    border: "1px solid #273044",
    background: "#0a0d14",
    overflow: "hidden",
  },
  slideLayoutName: {
    color: "#f4f6fa",
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1.25,
  },
  slideLayoutMeta: {
    color: "#7d89a3",
    fontSize: 11,
  },
  generatorPanel: {
    marginTop: 14,
    padding: 12,
    borderRadius: 8,
    border: "1px solid #20283a",
    background: "#0c1019",
    display: "grid",
    gap: 10,
  },
} satisfies Record<string, CSSProperties>;
