import type { CSSProperties } from "react";
import { EXPORT_H, EXPORT_W } from "./editorUtils";

const baseFont =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif";

export const styles = {
  shell: {
    display: "flex",
    width: "100%",
    height: "100dvh",
    overflow: "hidden",
    background: "#0a0d14",
    color: "#e6ebf5",
    fontFamily: baseFont,
  },
  sidebar: {
    width: 230,
    flexShrink: 0,
    borderRight: "1px solid #20283a",
    background: "#10141e",
    display: "flex",
    flexDirection: "column",
  },
  header: { padding: 18, borderBottom: "1px solid #20283a" },
  eyebrow: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: 1.8,
    color: "#6a7894",
  },
  titleInput: {
    marginTop: 8,
    width: "100%",
    border: "none",
    background: "transparent",
    color: "#f4f6fa",
    fontSize: 18,
    fontWeight: 700,
    outline: "none",
    padding: 0,
  },
  meta: { marginTop: 4, fontSize: 12, color: "#7d89a3" },
  thumbs: { flex: 1, overflowY: "auto", padding: 14, display: "grid", gap: 12 },
  thumbRow: {
    display: "grid",
    gridTemplateColumns: "22px 1fr",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: 6,
    border: "1px solid #242c3e",
    borderRadius: 7,
    background: "#0c1019",
    color: "#e6ebf5",
    cursor: "pointer",
  },
  thumbNumber: {
    color: "#7d89a3",
    fontSize: 11,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
  },
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  topbar: {
    height: 62,
    flexShrink: 0,
    padding: "0 22px",
    borderBottom: "1px solid #20283a",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
  },
  currentTitle: { fontSize: 15, fontWeight: 700, color: "#f4f6fa" },
  toolbar: { display: "inline-flex", alignItems: "center", gap: 10 },
  primaryButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 7,
    border: "none",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
  },
  workArea: {
    flex: 1,
    minHeight: 0,
    display: "flex",
  },
  stagePanel: {
    minWidth: 0,
    minHeight: 0,
    padding: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  slideFrame: {
    position: "relative",
    flexShrink: 0,
  },
  slideEditButton: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 5,
    height: 34,
    padding: "0 14px",
    borderRadius: 7,
    border: "1px solid rgba(255,255,255,0.22)",
    background: "rgba(16,20,30,0.88)",
    color: "#f4f6fa",
    boxShadow: "0 10px 28px rgba(0,0,0,0.28)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  inlineTextToolbar: {
    position: "absolute",
    zIndex: 8,
    display: "inline-flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    minHeight: 36,
    maxWidth: "calc(100% - 16px)",
    padding: "4px 6px",
    borderRadius: 7,
    border: "1px solid rgba(255,255,255,0.18)",
    background: "rgba(16,20,30,0.94)",
    boxShadow: "0 12px 34px rgba(0,0,0,0.28)",
  },
  inlineTextButton: {
    width: 28,
    height: 28,
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#151a25",
    color: "#f4f6fa",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
  },
  inlineTextButtonActive: {
    borderColor: "#d4a24c",
    background: "#2c2418",
    color: "#ffd991",
  },
  inlineDangerButton: {
    borderColor: "#ff8a8f",
    background: "#b4232a",
    color: "#fff",
  },
  inlineFontSize: {
    width: 54,
    height: 28,
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    color: "#f4f6fa",
    padding: "0 6px",
    font: `12px ${baseFont}`,
    outline: "none",
  },
  inlineColor: {
    width: 30,
    height: 28,
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    padding: 3,
    cursor: "pointer",
  },
  inlineSelect: {
    height: 28,
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    color: "#f4f6fa",
    padding: "0 7px",
    font: `12px ${baseFont}`,
    outline: "none",
    cursor: "pointer",
  },
  inlineFileLabel: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#151a25",
    color: "#f4f6fa",
    padding: "0 9px",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  inlineActionButton: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #d4a24c",
    background: "#2c2418",
    color: "#ffd991",
    padding: "0 9px",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  inlineHiddenInput: {
    display: "none",
  },
  inlineOpacity: {
    width: 74,
    accentColor: "#d4a24c",
    cursor: "pointer",
  },
  inlineTextEditor: {
    position: "absolute",
    zIndex: 7,
    boxSizing: "border-box",
    border: "1px solid #6f93ff",
    outline: "none",
    resize: "none",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    background: "rgba(255,255,255,0.02)",
  },
  inspector: {
    borderLeft: "1px solid #20283a",
    background: "#10141e",
    padding: 18,
    overflowY: "auto",
  },
  drawerBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    display: "flex",
    justifyContent: "flex-end",
    background: "rgba(3, 7, 18, 0.5)",
  },
  drawer: {
    width: 360,
    maxWidth: "calc(100vw - 28px)",
    height: "100%",
    boxSizing: "border-box",
    borderLeft: "1px solid #273044",
    background: "#10141e",
    boxShadow: "-24px 0 70px rgba(0,0,0,0.44)",
    padding: 18,
    overflowY: "auto",
  },
  drawerHint: {
    margin: "-6px 0 16px",
    color: "#7d89a3",
    fontSize: 12,
    lineHeight: 1.45,
  },
  inspectorHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
    marginBottom: 18,
  },
  inspectorTitle: {
    margin: "6px 0 0",
    fontSize: 18,
    lineHeight: 1.2,
    color: "#f4f6fa",
  },
  iconRow: { display: "inline-flex", gap: 8 },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    cursor: "pointer",
    fontSize: 16,
  },
  form: { display: "grid", gap: 14 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  field: {
    display: "grid",
    gap: 7,
    fontSize: 12,
    fontWeight: 700,
    color: "#9aa7bd",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px ${baseFont}`,
    outline: "none",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px/1.4 ${baseFont}`,
    resize: "vertical",
    outline: "none",
  },
  colorInput: {
    width: "100%",
    height: 38,
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    padding: 4,
  },
  toggleRow: { display: "flex", gap: 14 },
  itemList: {
    display: "grid",
    gap: 8,
  },
  itemRow: {
    display: "grid",
    gridTemplateColumns: "1fr 34px",
    gap: 8,
    alignItems: "center",
  },
  gridItemEditor: {
    display: "grid",
    gap: 8,
    padding: 8,
    borderRadius: 7,
    border: "1px solid #20283a",
    background: "#0c1019",
  },
  checkLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: "#d8dfed",
    fontSize: 13,
    fontWeight: 700,
  },
  addGrid: {
    marginTop: 20,
    paddingTop: 18,
    borderTop: "1px solid #20283a",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  secondaryButton: {
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 700,
    cursor: "pointer",
  },
  smallButton: {
    width: 34,
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 800,
    cursor: "pointer",
  },
  segmented: {
    display: "inline-flex",
    padding: 3,
    borderRadius: 8,
    border: "1px solid #2b3448",
    background: "#10141e",
  },
  segment: {
    height: 28,
    padding: "0 10px",
    borderRadius: 6,
    border: "none",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  hiddenStages: {
    position: "fixed",
    left: -10000,
    top: 0,
    width: EXPORT_W,
    height: EXPORT_H,
    overflow: "hidden",
    pointerEvents: "none",
  },
  ghostButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "transparent",
    color: "#e6ebf5",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
  },
  splitButton: {
    position: "relative",
    display: "inline-flex",
    alignItems: "stretch",
    height: 36,
    borderRadius: 7,
    overflow: "visible",
    boxShadow: "0 0 0 1px rgba(0,0,0,0.0)",
  },
  splitButtonMain: {
    height: 36,
    padding: "0 14px",
    borderRadius: "7px 0 0 7px",
    border: "none",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
  },
  splitButtonCaret: {
    height: 36,
    width: 30,
    border: "none",
    borderLeft: "1px solid rgba(7,20,37,0.25)",
    borderRadius: "0 7px 7px 0",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
    fontSize: 11,
  },
  exportMenu: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    minWidth: 240,
    padding: 6,
    borderRadius: 9,
    border: "1px solid #2b3448",
    background: "#10141e",
    boxShadow: "0 18px 44px rgba(0,0,0,0.5)",
    display: "grid",
    gap: 2,
    zIndex: 40,
  },
  exportMenuItem: {
    display: "block",
    textAlign: "left",
    padding: "9px 10px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: "#e6ebf5",
    cursor: "pointer",
    width: "100%",
  },
  exportMenuItemActive: {
    background: "#1a2030",
    borderColor: "#2b3448",
  },
  exportMenuItemHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  exportMenuItemLabel: {
    fontSize: 13,
    fontWeight: 800,
    color: "#f4f6fa",
  },
  exportMenuItemCheck: {
    color: "#d4a24c",
    fontWeight: 800,
  },
  exportMenuItemDesc: {
    marginTop: 3,
    fontSize: 11.5,
    color: "#7d89a3",
    lineHeight: 1.35,
  },
} satisfies Record<string, CSSProperties>;

export const presentStyles = {
  root: {
    position: "fixed",
    inset: 0,
    zIndex: 60,
    background: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  stageWrap: {
    position: "relative",
    background: "#000",
  },
  controls: {
    position: "absolute",
    bottom: 22,
    left: "50%",
    transform: "translateX(-50%)",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 999,
    background: "rgba(16,20,30,0.78)",
    border: "1px solid rgba(255,255,255,0.12)",
    boxShadow: "0 18px 48px rgba(0,0,0,0.5)",
    color: "#f4f6fa",
    transition: "opacity 200ms ease",
  },
  controlButton: {
    minWidth: 36,
    height: 32,
    padding: "0 10px",
    borderRadius: 999,
    border: "none",
    background: "transparent",
    color: "#f4f6fa",
    fontSize: 16,
    fontWeight: 800,
    cursor: "pointer",
  },
  exitButton: {
    fontSize: 11,
    letterSpacing: 1,
    background: "rgba(255,255,255,0.08)",
  },
  counter: {
    minWidth: 64,
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
    fontSize: 12,
    fontWeight: 700,
    color: "#d8dfed",
  },
} satisfies Record<string, CSSProperties>;
