import type { CSSProperties } from "react";

export const baseFont =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif";

export const styles = {
  eyebrow: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: 1.8,
    color: "#6a7894",
  },
  primaryButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 7,
    border: "none",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
  },
  inspector: {
    borderLeft: "1px solid #20283a",
    background: "#10141e",
    padding: 18,
    overflowY: "auto",
  },
  panelTitle: {
    color: "#f4f6fa",
    fontSize: 13,
    fontWeight: 800,
  },
  form: { display: "grid", gap: 14 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  field: {
    display: "grid",
    gap: 7,
    fontSize: 12,
    fontWeight: 700,
    color: "#9aa7bd",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px ${baseFont}`,
    outline: "none",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px/1.4 ${baseFont}`,
    resize: "vertical",
    outline: "none",
  },
  colorInput: {
    width: "100%",
    height: 38,
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    padding: 4,
  },
  toggleRow: { display: "flex", gap: 14 },
  itemList: {
    display: "grid",
    gap: 8,
  },
  itemRow: {
    display: "grid",
    gridTemplateColumns: "1fr 34px",
    gap: 8,
    alignItems: "center",
  },
  gridItemEditor: {
    display: "grid",
    gap: 8,
    padding: 8,
    borderRadius: 7,
    border: "1px solid #20283a",
    background: "#0c1019",
  },
  checkLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: "#d8dfed",
    fontSize: 13,
    fontWeight: 700,
  },
  secondaryButton: {
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 700,
    cursor: "pointer",
  },
  smallButton: {
    width: 34,
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 800,
    cursor: "pointer",
  },
  segmented: {
    display: "inline-flex",
    padding: 3,
    borderRadius: 8,
    border: "1px solid #2b3448",
    background: "#10141e",
  },
  segment: {
    height: 28,
    padding: "0 10px",
    borderRadius: 6,
    border: "none",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  ghostButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "transparent",
    color: "#e6ebf5",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
  },
  splitButton: {
    position: "relative",
    display: "inline-flex",
    alignItems: "stretch",
    height: 36,
    borderRadius: 7,
    overflow: "visible",
    boxShadow: "0 0 0 1px rgba(0,0,0,0.0)",
  },
  splitButtonMain: {
    height: 36,
    padding: "0 14px",
    borderRadius: "7px 0 0 7px",
    border: "none",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
  },
  splitButtonCaret: {
    height: 36,
    width: 30,
    border: "none",
    borderLeft: "1px solid rgba(7,20,37,0.25)",
    borderRadius: "0 7px 7px 0",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
    fontSize: 11,
  },
  exportMenu: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    minWidth: 240,
    padding: 6,
    borderRadius: 9,
    border: "1px solid #2b3448",
    background: "#10141e",
    boxShadow: "0 18px 44px rgba(0,0,0,0.5)",
    display: "grid",
    gap: 2,
    zIndex: 40,
  },
  exportMenuItem: {
    display: "block",
    textAlign: "left",
    padding: "9px 10px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: "#e6ebf5",
    cursor: "pointer",
    width: "100%",
  },
  exportMenuItemActive: {
    background: "#1a2030",
    borderColor: "#2b3448",
  },
  exportMenuItemHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  exportMenuItemLabel: {
    fontSize: 13,
    fontWeight: 800,
    color: "#f4f6fa",
  },
  exportMenuItemCheck: {
    color: "#d4a24c",
    fontWeight: 800,
  },
  exportMenuItemDesc: {
    marginTop: 3,
    fontSize: 11.5,
    color: "#7d89a3",
    lineHeight: 1.35,
  },
} satisfies Record<string, CSSProperties>;
