import type { CSSProperties } from "react";

export const baseFont =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif";

export const styles = {
  eyebrow: {
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: 1.8,
    color: "#6a7894",
  },
  primaryButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 7,
    border: "none",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
  },
  inlineTextToolbar: {
    position: "absolute",
    zIndex: 8,
    display: "inline-flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    minHeight: 36,
    maxWidth: "calc(100% - 16px)",
    padding: "4px 6px",
    borderRadius: 7,
    border: "1px solid rgba(255,255,255,0.18)",
    background: "rgba(16,20,30,0.94)",
    boxShadow: "0 12px 34px rgba(0,0,0,0.28)",
  },
  inlineTextButton: {
    width: 28,
    height: 28,
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#151a25",
    color: "#f4f6fa",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
  },
  inlineTextButtonActive: {
    borderColor: "#d4a24c",
    background: "#2c2418",
    color: "#ffd991",
  },
  inlineDangerButton: {
    borderColor: "#ff8a8f",
    background: "#b4232a",
    color: "#fff",
  },
  inlineFontSize: {
    width: 54,
    height: 28,
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    color: "#f4f6fa",
    padding: "0 6px",
    font: `12px ${baseFont}`,
    outline: "none",
  },
  inlineColor: {
    width: 30,
    height: 28,
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    padding: 3,
    cursor: "pointer",
  },
  inlineSelect: {
    height: 28,
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#0a0d14",
    color: "#f4f6fa",
    padding: "0 7px",
    font: `12px ${baseFont}`,
    outline: "none",
    cursor: "pointer",
  },
  inlineFileLabel: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #30384b",
    background: "#151a25",
    color: "#f4f6fa",
    padding: "0 9px",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  inlineActionButton: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    borderRadius: 5,
    border: "1px solid #d4a24c",
    background: "#2c2418",
    color: "#ffd991",
    padding: "0 9px",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  inlineOpacity: {
    width: 74,
    accentColor: "#d4a24c",
    cursor: "pointer",
  },
  inlineTextEditor: {
    position: "absolute",
    zIndex: 7,
    boxSizing: "border-box",
    border: "1px solid #6f93ff",
    outline: "none",
    resize: "none",
    overflow: "hidden",
    padding: 0,
    margin: 0,
    background: "rgba(255,255,255,0.02)",
  },
  inspector: {
    borderLeft: "1px solid #20283a",
    background: "#10141e",
    padding: 18,
    overflowY: "auto",
  },
  panelTitle: {
    color: "#f4f6fa",
    fontSize: 13,
    fontWeight: 800,
  },
  form: { display: "grid", gap: 14 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  field: {
    display: "grid",
    gap: 7,
    fontSize: 12,
    fontWeight: 700,
    color: "#9aa7bd",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px ${baseFont}`,
    outline: "none",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box",
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    color: "#e6ebf5",
    padding: "9px 10px",
    font: `13px/1.4 ${baseFont}`,
    resize: "vertical",
    outline: "none",
  },
  colorInput: {
    width: "100%",
    height: 38,
    borderRadius: 6,
    border: "1px solid #2b3448",
    background: "#0a0d14",
    padding: 4,
  },
  toggleRow: { display: "flex", gap: 14 },
  itemList: {
    display: "grid",
    gap: 8,
  },
  itemRow: {
    display: "grid",
    gridTemplateColumns: "1fr 34px",
    gap: 8,
    alignItems: "center",
  },
  gridItemEditor: {
    display: "grid",
    gap: 8,
    padding: 8,
    borderRadius: 7,
    border: "1px solid #20283a",
    background: "#0c1019",
  },
  checkLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    color: "#d8dfed",
    fontSize: 13,
    fontWeight: 700,
  },
  secondaryButton: {
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 700,
    cursor: "pointer",
  },
  smallButton: {
    width: 34,
    height: 34,
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "#161b27",
    color: "#d8dfed",
    fontWeight: 800,
    cursor: "pointer",
  },
  segmented: {
    display: "inline-flex",
    padding: 3,
    borderRadius: 8,
    border: "1px solid #2b3448",
    background: "#10141e",
  },
  segment: {
    height: 28,
    padding: "0 10px",
    borderRadius: 6,
    border: "none",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
  },
  ghostButton: {
    height: 36,
    padding: "0 14px",
    borderRadius: 7,
    border: "1px solid #2b3448",
    background: "transparent",
    color: "#e6ebf5",
    fontWeight: 700,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
  },
  splitButton: {
    position: "relative",
    display: "inline-flex",
    alignItems: "stretch",
    height: 36,
    borderRadius: 7,
    overflow: "visible",
    boxShadow: "0 0 0 1px rgba(0,0,0,0.0)",
  },
  splitButtonMain: {
    height: 36,
    padding: "0 14px",
    borderRadius: "7px 0 0 7px",
    border: "none",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
  },
  splitButtonCaret: {
    height: 36,
    width: 30,
    border: "none",
    borderLeft: "1px solid rgba(7,20,37,0.25)",
    borderRadius: "0 7px 7px 0",
    background: "#d4a24c",
    color: "#071425",
    fontWeight: 800,
    cursor: "pointer",
    fontSize: 11,
  },
  exportMenu: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    minWidth: 240,
    padding: 6,
    borderRadius: 9,
    border: "1px solid #2b3448",
    background: "#10141e",
    boxShadow: "0 18px 44px rgba(0,0,0,0.5)",
    display: "grid",
    gap: 2,
    zIndex: 40,
  },
  exportMenuItem: {
    display: "block",
    textAlign: "left",
    padding: "9px 10px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    color: "#e6ebf5",
    cursor: "pointer",
    width: "100%",
  },
  exportMenuItemActive: {
    background: "#1a2030",
    borderColor: "#2b3448",
  },
  exportMenuItemHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  exportMenuItemLabel: {
    fontSize: 13,
    fontWeight: 800,
    color: "#f4f6fa",
  },
  exportMenuItemCheck: {
    color: "#d4a24c",
    fontWeight: 800,
  },
  exportMenuItemDesc: {
    marginTop: 3,
    fontSize: 11.5,
    color: "#7d89a3",
    lineHeight: 1.35,
  },
} satisfies Record<string, CSSProperties>;

export const presentStyles = {
  root: {
    position: "fixed",
    inset: 0,
    zIndex: 60,
    background: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  stageWrap: {
    position: "relative",
    background: "#000",
  },
  controls: {
    position: "absolute",
    bottom: 22,
    left: "50%",
    transform: "translateX(-50%)",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 999,
    background: "rgba(16,20,30,0.78)",
    border: "1px solid rgba(255,255,255,0.12)",
    boxShadow: "0 18px 48px rgba(0,0,0,0.5)",
    color: "#f4f6fa",
    transition: "opacity 200ms ease",
  },
  controlButton: {
    minWidth: 36,
    height: 32,
    padding: "0 10px",
    borderRadius: 999,
    border: "none",
    background: "transparent",
    color: "#f4f6fa",
    fontSize: 16,
    fontWeight: 800,
    cursor: "pointer",
  },
  exitButton: {
    fontSize: 11,
    letterSpacing: 1,
    background: "rgba(255,255,255,0.08)",
  },
  counter: {
    minWidth: 64,
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
    fontSize: 12,
    fontWeight: 700,
    color: "#d8dfed",
  },
} satisfies Record<string, CSSProperties>;
